"""CollabSessions: Multi-agent collaboration subsystem for OpenLMLib."""

from .db import (
    connect_collab_db,
    init_collab_db,
    create_session,
    get_session,
    list_sessions,
    update_session_status,
    insert_agent,
    get_session_agents,
    insert_message,
    get_messages,
    get_messages_since,
    get_messages_tail,
    grep_messages,
    get_message_range,
    insert_task,
    update_task_status,
    get_session_tasks,
    insert_artifact,
    get_session_artifacts,
    get_session_state,
    update_session_state,
)
from .session import (
    create_collab_session,
    join_collab_session,
    leave_collab_session,
    terminate_collab_session,
)
from .message_bus import MessageBus
from .context_compiler import ContextCompiler
from .artifact_store import ArtifactStore
from .state_manager import StateManager
from .rules_engine import RulesEngine, DEFAULT_RULES
from .compactor import SessionCompactor
from .prompts import (
    ORCHESTRATOR_SYSTEM_PROMPT,
    WORKER_SYSTEM_PROMPT,
    OBSERVER_SYSTEM_PROMPT,
    PROMPT_TEMPLATES,
    get_system_prompt,
    list_available_roles,
)
from .errors import (
    CollabError,
    SessionNotFoundError,
    SessionNotActiveError,
    SessionFullError,
    AgentNotFoundError,
    AgentNotAuthorizedError,
    StateConflictError,
    ArtifactNotFoundError,
    TemplateNotFoundError,
    InvalidMessageTypeError,
    MessageTooLongError,
    InvalidRoleError,
    DatabaseError,
    FilesystemError,
    SecurityError,
    VALID_MESSAGE_TYPES,
    VALID_ROLES,
    VALID_SESSION_STATUSES,
    VALID_AGENT_STATUSES,
    VALID_TASK_STATUSES,
    make_error_response,
    error_from_exception,
)
from .security import (
    validate_session_id,
    validate_agent_id,
    validate_artifact_id,
    validate_message_type,
    validate_message_content,
    sanitize_content,
    verify_agent_in_session,
    verify_session_exists_and_active,
    verify_orchestrator,
    validate_safe_path,
)

__all__ = [
    # DB
    "connect_collab_db",
    "init_collab_db",
    "create_collab_session",
    "join_collab_session",
    "leave_collab_session",
    "terminate_collab_session",
    "MessageBus",
    "ContextCompiler",
    "ArtifactStore",
    "StateManager",
    "RulesEngine",
    "DEFAULT_RULES",
    "SessionCompactor",
    "create_session",
    "get_session",
    "list_sessions",
    "update_session_status",
    "insert_agent",
    "get_session_agents",
    "insert_message",
    "get_messages",
    "get_messages_since",
    "get_messages_tail",
    "grep_messages",
    "get_message_range",
    "insert_task",
    "update_task_status",
    "get_session_tasks",
    "insert_artifact",
    "get_session_artifacts",
    "get_session_state",
    "update_session_state",
    # Prompts
    "ORCHESTRATOR_SYSTEM_PROMPT",
    "WORKER_SYSTEM_PROMPT",
    "OBSERVER_SYSTEM_PROMPT",
    "PROMPT_TEMPLATES",
    "get_system_prompt",
    "list_available_roles",
    # Errors
    "CollabError",
    "SessionNotFoundError",
    "SessionNotActiveError",
    "SessionFullError",
    "AgentNotFoundError",
    "AgentNotAuthorizedError",
    "StateConflictError",
    "ArtifactNotFoundError",
    "TemplateNotFoundError",
    "InvalidMessageTypeError",
    "MessageTooLongError",
    "InvalidRoleError",
    "DatabaseError",
    "FilesystemError",
    "SecurityError",
    "VALID_MESSAGE_TYPES",
    "VALID_ROLES",
    "VALID_SESSION_STATUSES",
    "VALID_AGENT_STATUSES",
    "VALID_TASK_STATUSES",
    "make_error_response",
    "error_from_exception",
    # Security
    "validate_session_id",
    "validate_agent_id",
    "validate_artifact_id",
    "validate_message_type",
    "validate_message_content",
    "sanitize_content",
    "verify_agent_in_session",
    "verify_session_exists_and_active",
    "verify_orchestrator",
    "validate_safe_path",
]
